### ISSUE TITLE
Make tunnelmole errors managable (try/catch)

### ISSUE THREAD

**Issue by mi-skam** [robbie-cahill/tunnelmole-service#10]
Let's say you are offline, invoking tunnelmole timesout at some point, but does not respect a try-catch clause.

```js
import { tunnelmole } from 'tunnelmole';

// starting tunnelmole
let tunnelmoleUrl;
try {
  await tunnelmole({
    port: 8888,
  });
} catch (err) {
  console.error('Cannot reach tunnelmole. Offline? 🙃');
}
```

returns
```shell
1700490649117Caught an error:
Error: getaddrinfo EAI_AGAIN service.tunnelmole.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'service.tunnelmole.com'
}``` and not Cannot reach tunnelmole. Offline? 🙃'

**Comment by robbie-cahill** [comment]
Looks like this belongs in the client project https://github.com/robbie-cahill/tunnelmole-client.

The client does have a global exception handler. To implement this would require re-throwing the exception or just removing this handler. I guess that is possible, but that might result in the client crashing in certain cases when it might be able to carry on.
