### ISSUE TITLE
Self hosted Tunnelmole client

### ISSUE THREAD

**Issue by Somnath-Pandey-Vested** [robbie-cahill/tunnelmole-service#13]
I am trying to setup the self hosted tunnelmole service and client. I had setup the Tunnelmole service, it is up and running. when i am trying to setup the tunnelmole client, based on the documentation it should generate two urls after running the below command
`npm run build && node dist/src/index.js 3000`
Its not bale to generate fro me. Below is my config-instance.ts
`const instanceConfig = {
    hostip: {
        endpoint: "wss://tunnelmole.vested.com:8081",  // Change to your server's domain
        httpEndpoint: "http://tunnelmole.vested.com:8081",
    },
    runtime: {
        debug: true,
        enableLogging: true
    }
}

export default instanceConfig;`
I am running it on a remote server which has puclic ip and a domain is assosciated to it. 
Below is my tunnelmole-service config-instance.toml
`[server]
httpPort = 8080
websocketPort = 8081
domain = 'tunnelmole.vestedfinance.com'  # Change to your server's domain
password = 'test'  # Update the password

###
# MySQL is used for Logging wnen it is enabled
###
[mysql]
host = 'localhost'
user = 'root'
password = 'changeme'
database = 'tunnelmole'

###
# Enable or disable debug output and logging
###
[runtime]
debug = true
enableLogging = false
`
@robbie-cahill can you help me out here?

**Comment by robbie-cahill** [comment]
Looks interesting, i'd like to find out more information, can you send me an email privately at robbie-cahill@proton.me and we can see what options are available to help out here?
