### ISSUE TITLE
Self Hosted with Client, Client just closes

### ISSUE THREAD

**Issue by KarthikHebbarMN** [robbie-cahill/tunnelmole-service#7]
Tried self hosting the solution. 
Started by starting the server using npm start and tried connecting to it using client 
`node dist/src/index.js`
with this as config 
`const instanceConfig = {
    hostip: {
        endpoint: "ws://localhost:8080",
        httpEndpoint: ""//"https://service.tunnelmole.com"
    },
    runtime: {
        debug:true,
        enableLogging: true
    }
}`

When i do that nothing happens, I dont get any information as to redirect url and instead just when i hit enter it closes immediately.

**Comment by umeshtyagitvz** [comment]
I am also facing the same issue. @robbie-cahill  please address this issue.

**Comment by robbie-cahill** [comment]
If not just running locally, you'd have to deploy this to a server somewhere that has its own domain.

You need to update the `config-instance.ts` in the client to point to your server (localhost for local, or your domain).

You've also got to build before launching so the changes get compiled.

**Comment by robbie-cahill** [comment]
How did it go? What are you building with self hosting?

**Comment by robbie-cahill** [comment]
haven't heard anything more, so closing this, but feel free to reopen.
